from app.workflows.contracts import WorkflowTemplateContract


WORKFLOW_TEMPLATE_CONTRACTS = {
    "pod_lifecycle": WorkflowTemplateContract(
        workflow_name="pod_lifecycle",
        operation="pod",
        version="1.0.0",
        description="Unified POD lifecycle workflow with event-driven branches.",
        event_types=["route_completed", "email_received", "reminder_due"],
        required_state_keys=["event_type"],
        optional_state_keys=[
            "shipment_id",
            "load_id",
            "thread_id",
            "attachments",
            "workflow_lifecycle_payload",
            "to",
            "subject",
            "body",
            "account_id",
            "reminder_step",
        ],
    ),
    "ratecon": WorkflowTemplateContract(
        workflow_name="ratecon",
        operation="ratecon",
        version="1.0.0",
        description="Rate confirmation workflow; triggered by Unipile mail (email_received).",
        event_types=["email_received"],
        required_state_keys=["load_id"],
        optional_state_keys=[
            "event_type",
            "app_user_id",
            "thread_id",
            "shipment_id",
            "email_id",
            "account_id",
            "attachments",
            "has_attachments",
            "workflow_lifecycle_payload",
            "ratecon_lifecycle_thread_persist",
            "ratecon_s3_upload",
        ],
    ),
    "load_tendering": WorkflowTemplateContract(
        workflow_name="load_tendering",
        operation="load_tendering",
        version="1.0.0",
        description="Load tendering: log ingest context after spreadsheet email import.",
        event_types=[
            "email_received",
            "tender_created",
            "carrier_email_received",
            "ack_received",
            "reminder_due",
            "escalation_due",
        ],
        required_state_keys=["event_type"],
        optional_state_keys=[
            "workflow_name",
            "source_email_thread_id",
            "email_id",
            "account_id",
            "attachments",
            "has_attachments",
            "webhook_name",
            "data_import_id",
            "execution_id",
            "workflow_lifecycle_payload",
            "tenant_id",
            "load_id",
            "tender_id",
            "tender_row",
            "tender_row_index",
            "body",
            "body_plain",
            "thread_id",
            "workflow_lifecycle_id",
        ],
    ),
}
