WORKFLOW_CONFIGS = {
    "pod_lifecycle": {
        "entry": "route_event",
        "exit": "end",
        "nodes": [
            "route_event",
            "get_shipment",
            "read_workflow_lifecycle",
            "check_existing_pod",
            "send_email",
            "record_and_schedule_pod_request",
            "record_pod_started_activity",
            "record_pod_reminder_activity",
            "get_email_attachments",
            "load_ratecon_analysis",
            "classify_attachments",
            "record_pod_upload_activity",
            "pod_analysis",
            "record_pod_extraction_activity",
            "pod_vs_ratecon_analysis",
            "record_pod_vs_ratecon_activity",
            "record_pod_processed_activity",
            "upload_to_turvo",
            "record_pod_tms_upload_activity",
            "update_shipment",
            "end",
        ],
        "edges": [
            ["get_email_attachments", "load_ratecon_analysis"],
            ["classify_attachments", "record_pod_upload_activity"],
            ["record_pod_upload_activity", "pod_analysis"],
            ["pod_analysis", "record_pod_extraction_activity"],
            ["record_pod_extraction_activity", "pod_vs_ratecon_analysis"],
            ["pod_vs_ratecon_analysis", "record_pod_vs_ratecon_activity"],
            ["record_pod_vs_ratecon_activity", "record_pod_processed_activity"],
            ["record_pod_processed_activity", "update_shipment"],
            ["upload_to_turvo", "record_pod_tms_upload_activity"],
            ["update_shipment", "end"],
            ["send_email", "record_pod_reminder_activity"],
            ["record_pod_reminder_activity", "end"],
            ["record_and_schedule_pod_request", "record_pod_started_activity"],
            ["record_pod_started_activity", "end"],
        ],
        "routers": {
            "route_event": {
                "router": "event_type",
                "map": {
                    "route_completed": "get_shipment",
                    "email_received": "read_workflow_lifecycle",
                    "manual_pod_upload": "read_workflow_lifecycle",
                    "reminder_due": "check_existing_pod",
                },
            },
            "get_shipment": {
                "router": "shipment_router",
                # TODO: a common "missing" key instead of multiple keys mapping to same END node
                "map": {
                    "convoy": "end",
                    "non_convoy": "check_existing_pod",
                    # Pod reply workflow
                    "valid_shipment_status": "get_email_attachments",
                    "manual_pod_valid": "upload_to_turvo",
                    "invalid_shipment_status": "end",
                },
            },
            "check_existing_pod": {
                "router": "pod_missing_dispatch",
                "map": {
                    "exists": "end",
                    "schedule_initial": "record_and_schedule_pod_request",  # no send_email on initial
                    "send_now": "send_email",  # reminder_due path
                    "skip_send": "end",
                },
            },
            "read_workflow_lifecycle": {
                "router": "read_workflow_lifecycle_router",
                "map": {"is_found": "get_shipment", "missing": "end"},
            },
            "load_ratecon_analysis": {
                "router": "ratecon_cache_router",
                "map": {"ready": "classify_attachments", "missing": "end"},
            },
            "record_pod_tms_upload_activity": {
                "router": "manual_tms_upload_router",
                "map": {"continue": "load_ratecon_analysis", "stop": "end"},
            },
        },
    },
    "ratecon": {
        "entry": "resolve_load_to_shipment",
        "exit": "end",
        "nodes": [
            "resolve_load_to_shipment",
            "get_shipment",
            "link_shipment_locations",
            "resolve_workflow_lifecycle",
            "record_ratecon_received_activity",
            "upload_ratecon_attachments",
            "record_ratecon_upload_activity",
            "ratecon_analysis",
            "record_ratecon_processed_activity",
            "enqueue_driver_assignment_on_ratecon_complete",
            "check_ratecon_workflow_lifecycle",
            "end",
        ],
        "edges": [
            ["resolve_load_to_shipment", "get_shipment"],
            ["get_shipment", "link_shipment_locations"],
            ["link_shipment_locations", "resolve_workflow_lifecycle"],
            ["resolve_workflow_lifecycle", "record_ratecon_received_activity"],
            ["record_ratecon_received_activity", "upload_ratecon_attachments"],
            ["upload_ratecon_attachments", "record_ratecon_upload_activity"],
            ["record_ratecon_upload_activity", "ratecon_analysis"],
            ["ratecon_analysis", "record_ratecon_processed_activity"],
            [
                "record_ratecon_processed_activity",
                "enqueue_driver_assignment_on_ratecon_complete",
            ],
            [
                "enqueue_driver_assignment_on_ratecon_complete",
                "check_ratecon_workflow_lifecycle",
            ],
            ["check_ratecon_workflow_lifecycle", "end"],
        ],
        "routers": {},
    },
    "driver_assignment": {
        "entry": "route_event",
        "exit": "end",
        "nodes": [
            "route_event",
            "get_shipment",
            "check_driver_assignment_eligibility",
            "check_driver_reminder_eligibility",
            "check_driver_escalation_eligibility",
            "route_driver_assignment_delayed_event",
            "resolve_workflow_lifecycle",
            "schedule_driver_reminders",
            "record_driver_assignment_started",
            "send_driver_reminder",
            "record_driver_reminder_sent",
            "classify_driver_details",
            "route_tms_searchable",
            "resolve_turvo_driver",
            "record_tms_driver_success",
            "record_tms_driver_not_resolved",
            "record_tms_driver_error",
            "send_driver_details_confirmation",
            "record_driver_details_confirmation_sent",
            "record_driver_assignment_completed",
            "send_driver_details_partial_follow_up",
            "escalate_driver_assignment",
            "end",
        ],
        "edges": [
            ["resolve_workflow_lifecycle", "schedule_driver_reminders"],
            ["schedule_driver_reminders", "record_driver_assignment_started"],
            ["record_driver_assignment_started", "end"],
            ["get_shipment", "route_driver_assignment_delayed_event"],
            ["escalate_driver_assignment", "end"],
            ["send_driver_reminder", "record_driver_reminder_sent"],
            ["record_driver_reminder_sent", "end"],
            ["send_driver_details_partial_follow_up", "record_driver_reminder_sent"],
            ["record_tms_driver_not_resolved", "send_driver_details_partial_follow_up"],
            ["record_tms_driver_success", "send_driver_details_confirmation"],
            ["send_driver_details_confirmation", "record_driver_details_confirmation_sent"],
            [
                "record_driver_details_confirmation_sent",
                "record_driver_assignment_completed",
            ],
            ["record_driver_assignment_completed", "end"],
            ["record_tms_driver_error", "end"],
        ],
        "routers": {
            "route_event": {
                "router": "event_type",
                "map": {
                    "ratecon_completed": "check_driver_assignment_eligibility",
                    "reminder_due": "get_shipment",
                    "escalation_due": "get_shipment",
                    "driver_details_email_received": "classify_driver_details",
                },
            },
            "route_driver_assignment_delayed_event": {
                "router": "driver_assignment_delayed_event_router",
                "map": {
                    "reminder_due": "check_driver_reminder_eligibility",
                    "escalation_due": "check_driver_escalation_eligibility",
                },
            },
            "check_driver_assignment_eligibility": {
                "router": "driver_assignment_eligibility_router",
                "map": {"eligible": "resolve_workflow_lifecycle", "skip": "end"},
            },
            "check_driver_reminder_eligibility": {
                "router": "driver_assignment_eligibility_router",
                "map": {"eligible": "send_driver_reminder", "skip": "end"},
            },
            "check_driver_escalation_eligibility": {
                "router": "driver_assignment_eligibility_router",
                "map": {"eligible": "escalate_driver_assignment", "skip": "end"},
            },
            "classify_driver_details": {
                "router": "driver_details_router",
                "map": {
                    "has_details": "resolve_turvo_driver",
                    "insufficient": "route_tms_searchable",
                    "do_nothing": "end",
                },
            },
            "route_tms_searchable": {
                "router": "tms_searchable_router",
                "map": {
                    "searchable": "resolve_turvo_driver",
                    "follow_up_only": "send_driver_details_partial_follow_up",
                    "none": "end",
                },
            },
            "resolve_turvo_driver": {
                "router": "tms_driver_router",
                "map": {
                    "assigned": "record_tms_driver_success",
                    "follow_up": "record_tms_driver_not_resolved",
                    "error": "record_tms_driver_error",
                },
            },
        },
    },
    "load_tendering": {
        "entry": "route_event",
        "exit": "end",
        "nodes": [
            "route_event",
            "record_tender_created_activity",
            "calculate_tender_params",
            "send_tender_email",
            "log_tender_activity",
            "record_tender_sent_to_carrier",
            "schedule_tender_reminders",
            "guard_automatic_reply_ack",
            "classify_carrier_ack",
            "record_ack_received",
            "read_tender_row",
            "resolve_international_delivery_skip",
            "resolve_pack_code_skip",
            "record_tender_business_warnings",
            "send_tender_reminder",
            "update_reminder_status",
            "escalate_tender",
            "end",
        ],
        "edges": [
            ["record_tender_created_activity", "read_tender_row"],
            ["resolve_international_delivery_skip", "end"],
            ["resolve_pack_code_skip", "end"],
            ["send_tender_email", "record_tender_business_warnings"],
            ["record_tender_business_warnings", "log_tender_activity"],
            ["log_tender_activity", "end"],
            ["record_tender_sent_to_carrier", "schedule_tender_reminders"],
            ["schedule_tender_reminders", "end"],
            ["record_ack_received", "end"],
            ["send_tender_reminder", "update_reminder_status"],
            ["update_reminder_status", "end"],
            ["escalate_tender", "end"],
        ],
        "routers": {
            "route_event": {
                "router": "event_type",
                "map": {
                    "tender_created": "record_tender_created_activity",
                    "carrier_email_received": "record_tender_sent_to_carrier",
                    "ack_received": "guard_automatic_reply_ack",
                    "reminder_due": "read_tender_row",
                    "escalation_due": "read_tender_row",
                },
            },
            "calculate_tender_params": {
                "router": "load_type_router",
                "map": {
                    "ltl_path": "send_tender_email",
                    "ftl_path": "send_tender_email",
                },
            },
            "read_tender_row": {
                "router": "post_read_tender_router",
                "map": {
                    "international": "resolve_international_delivery_skip",
                    "pack_code_skipped": "resolve_pack_code_skip",
                    "domestic": "calculate_tender_params",
                    "completed": "end",
                    "reminder_due": "send_tender_reminder",
                    "escalation_due": "escalate_tender",
                    "missing": "end",
                },
            },
            "guard_automatic_reply_ack": {
                "router": "automatic_reply_ack_router",
                "map": {
                    "skipped": "end",
                    "continue": "classify_carrier_ack",
                },
            },
            "classify_carrier_ack": {
                "router": "carrier_ack_router",
                "map": {
                    "accepted": "record_ack_received",
                    "rejected": "record_ack_received",
                    "do_nothing": "end",
                },
            },
        },
    },
}
