WORKFLOW_CONFIGS = {
    "pod_lifecycle": {
        "entry": "route_event",
        "exit": "end",
        "nodes": [
            "route_event",
            "get_shipment",
            "read_workflow_lifecycle",
            "check_existing_pod",
            "send_email",
            "record_and_schedule_pod_request",
            "record_pod_started_activity",
            "record_pod_reminder_activity",
            "get_email_attachments",
            "load_ratecon_analysis",
            "classify_attachments",
            "record_pod_upload_activity",
            "pod_analysis",
            "record_pod_extraction_activity",
            "pod_vs_ratecon_analysis",
            "record_pod_vs_ratecon_activity",
            "record_pod_processed_activity",
            "upload_to_turvo",
            "record_pod_tms_upload_activity",
            "update_shipment",
            "end",
        ],
        "edges": [
            ["get_email_attachments", "load_ratecon_analysis"],
            ["classify_attachments", "record_pod_upload_activity"],
            ["record_pod_upload_activity", "pod_analysis"],
            ["pod_analysis", "record_pod_extraction_activity"],
            ["record_pod_extraction_activity", "pod_vs_ratecon_analysis"],
            ["pod_vs_ratecon_analysis", "record_pod_vs_ratecon_activity"],
            ["record_pod_vs_ratecon_activity", "record_pod_processed_activity"],
            ["record_pod_processed_activity", "update_shipment"],
            ["upload_to_turvo", "record_pod_tms_upload_activity"],
            ["update_shipment", "end"],
            ["send_email", "record_pod_reminder_activity"],
            ["record_pod_reminder_activity", "end"],
            ["record_and_schedule_pod_request", "record_pod_started_activity"],
            ["record_pod_started_activity", "end"],
        ],
        "routers": {
            "route_event": {
                "router": "event_type",
                "map": {
                    "route_completed": "get_shipment",
                    "email_received": "read_workflow_lifecycle",
                    "manual_pod_upload": "read_workflow_lifecycle",
                    "reminder_due": "check_existing_pod",
                },
            },
            "get_shipment": {
                "router": "shipment_router",
                # TODO: a common "missing" key instead of multiple keys mapping to same END node
                "map": {
                    "convoy": "end",
                    "non_convoy": "check_existing_pod",
                    # Pod reply workflow
                    "valid_shipment_status": "get_email_attachments",
                    "manual_pod_valid": "upload_to_turvo",
                    "invalid_shipment_status": "end",
                },
            },
            "check_existing_pod": {
                "router": "pod_missing_dispatch",
                "map": {
                    "exists": "end",
                    "schedule_initial": "record_and_schedule_pod_request",  # no send_email on initial
                    "send_now": "send_email",  # reminder_due path
                    "skip_send": "end",
                },
            },
            "read_workflow_lifecycle": {
                "router": "read_workflow_lifecycle_router",
                "map": {"is_found": "get_shipment", "missing": "end"},
            },
            "load_ratecon_analysis": {
                "router": "ratecon_cache_router",
                "map": {"ready": "classify_attachments", "missing": "end"},
            },
            "record_pod_tms_upload_activity": {
                "router": "manual_tms_upload_router",
                "map": {"continue": "load_ratecon_analysis", "stop": "end"},
            },
        },
    },
    "ratecon": {
        "entry": "resolve_load_to_shipment",
        "exit": "end",
        "nodes": [
            "resolve_load_to_shipment",
            "get_shipment",
            "link_shipment_locations",
            "resolve_workflow_lifecycle",
            "record_ratecon_received_activity",
            "upload_ratecon_attachments",
            "record_ratecon_upload_activity",
            "ratecon_analysis",
            "record_ratecon_processed_activity",
            "check_ratecon_workflow_lifecycle",
            "end",
        ],
        "edges": [
            ["resolve_load_to_shipment", "get_shipment"],
            ["get_shipment", "link_shipment_locations"],
            ["link_shipment_locations", "resolve_workflow_lifecycle"],
            ["resolve_workflow_lifecycle", "record_ratecon_received_activity"],
            ["record_ratecon_received_activity", "upload_ratecon_attachments"],
            ["upload_ratecon_attachments", "record_ratecon_upload_activity"],
            ["record_ratecon_upload_activity", "ratecon_analysis"],
            ["ratecon_analysis", "record_ratecon_processed_activity"],
            ["record_ratecon_processed_activity", "check_ratecon_workflow_lifecycle"],
            ["check_ratecon_workflow_lifecycle", "end"],
        ],
        "routers": {},
    },
    "load_tendering": {
        "entry": "route_event",
        "exit": "end",
        "nodes": [
            "route_event",
            "record_tender_created_activity",
            "calculate_tender_params",
            "send_tender_email",
            "log_tender_activity",
            "record_tender_sent_to_carrier",
            "schedule_tender_reminders",
            "guard_automatic_reply_ack",
            "classify_carrier_ack",
            "record_ack_received",
            "read_tender_row",
            "complete_international_tender",
            "record_tender_business_warnings",
            "send_tender_reminder",
            "update_reminder_status",
            "escalate_tender",
            "end",
        ],
        "edges": [
            ["record_tender_created_activity", "read_tender_row"],
            ["complete_international_tender", "end"],
            ["send_tender_email", "record_tender_business_warnings"],
            ["record_tender_business_warnings", "log_tender_activity"],
            ["log_tender_activity", "end"],
            ["record_tender_sent_to_carrier", "schedule_tender_reminders"],
            ["schedule_tender_reminders", "end"],
            ["record_ack_received", "end"],
            ["send_tender_reminder", "update_reminder_status"],
            ["update_reminder_status", "end"],
            ["escalate_tender", "end"],
        ],
        "routers": {
            "route_event": {
                "router": "event_type",
                "map": {
                    "tender_created": "record_tender_created_activity",
                    "carrier_email_received": "record_tender_sent_to_carrier",
                    "ack_received": "guard_automatic_reply_ack",
                    "reminder_due": "read_tender_row",
                    "escalation_due": "read_tender_row",
                },
            },
            "calculate_tender_params": {
                "router": "load_type_router",
                "map": {
                    "ltl_path": "send_tender_email",
                    "ftl_path": "send_tender_email",
                },
            },
            "read_tender_row": {
                "router": "post_read_tender_router",
                "map": {
                    "international": "complete_international_tender",
                    "domestic": "calculate_tender_params",
                    "completed": "end",
                    "reminder_due": "send_tender_reminder",
                    "escalation_due": "escalate_tender",
                    "missing": "end",
                },
            },
            "guard_automatic_reply_ack": {
                "router": "automatic_reply_ack_router",
                "map": {
                    "skipped": "end",
                    "continue": "classify_carrier_ack",
                },
            },
            "classify_carrier_ack": {
                "router": "carrier_ack_router",
                "map": {
                    "accepted": "record_ack_received",
                    "rejected": "record_ack_received",
                    "do_nothing": "end",
                },
            },
        },
    },
}
