name: Deploy backend to Amazon ECS Production

on:
  push:
    branches:
      - staging

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: freightx-agents-backend
  ECS_CLUSTER: freightx-prod-cluster
  UVICORN_SERVICE: prod-freightx-agents-uvicorn-service-qkd892e1
  CELERY_SERVICE: prod-freightx-agents-celery-service-he3euvxv

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker buildx build \
          --platform linux/arm64 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --push .

    # --------------------------------------------------------- 
    # DEPLOY UVICORN ENVIRONMENT 
    # --------------------------------------------------------- 
    - name: Force ECS to deploy new image to uvicorn Service 
      run: | 
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.UVICORN_SERVICE }} \
          --force-new-deployment
    
    # --------------------------------------------------------- 
    # DEPLOY CELERY ENVIRONMENT 
    # --------------------------------------------------------- 

    - name: Force ECS to deploy new image to CELERY Service
      run: |
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.CELERY_SERVICE }} \
          --force-new-deployment
