name: Deploy backend to Amazon ECS Staging

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: freightx-agents-backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # - name: Get secrets.json
    #   run: |
    #     sudo apt-get install jq -y
    #     aws secretsmanager get-secret-value --secret-id ${{secrets.SECRETS_ARN}} | jq -r '.SecretString' >> secrets.json
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Force ECS to deploy new image
      run: |
        aws ecs update-service \
          --cluster freightx-staging-cluster \
          --service staging-freightx-agents-service-gq43l3i5 \
          --force-new-deployment
